USE $(DatabaseName)

GO

BEGIN TRY
    INSERT INTO Entries DEFAULT VALUES
END TRY
BEGIN CATCH
END CATCH

BEGIN TRY
    INSERT INTO MonthlyBudgets DEFAULT VALUES
END TRY
BEGIN CATCH
END CATCH

BEGIN TRY
    INSERT INTO Categories DEFAULT VALUES
END TRY
BEGIN CATCH
END CATCH

BEGIN TRY
    INSERT INTO Parties DEFAULT VALUES
END TRY
BEGIN CATCH
END CATCH

BEGIN TRY
    INSERT INTO Accounts DEFAULT VALUES
END TRY
BEGIN CATCH
END CATCH

BEGIN TRY
    INSERT INTO Users DEFAULT VALUES
END TRY
BEGIN CATCH
END CATCH

DELETE FROM Categories_MonthlyBudgets

DELETE FROM Entries
DBCC CHECKIDENT ('$(DatabaseName).dbo.Entries',RESEED, 0)

DELETE FROM MonthlyBudgets
DBCC CHECKIDENT ('$(DatabaseName).dbo.MonthlyBudgets',RESEED, 0)

DELETE FROM Categories
DBCC CHECKIDENT ('$(DatabaseName).dbo.Categories',RESEED, 0)

DELETE FROM Parties
DBCC CHECKIDENT ('$(DatabaseName).dbo.Parties',RESEED, 0)

DELETE FROM Accounts
DBCC CHECKIDENT ('$(DatabaseName).dbo.Accounts',RESEED, 0)

DELETE FROM Users
DBCC CHECKIDENT ('$(DatabaseName).dbo.Users',RESEED, 0)

GO
